---
abstract: 'Obtain Gold and Silver Fixings (Prices) from London Bullion Market '
author:
  - 'Thomas Fahle, C<< <cpan at thomas-fahle.de> >>, Thomas Fahle <cpan@thomas-fahle.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.25
  Test::More: 0
  Test::Warn: 0.22
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LBMA-Statistics
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0.41
  Encode: 2.23
  HTML::TableExtract: 2.10
  Log::Log4perl: 1.30
  WWW::Mechanize: 1.34
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tomfahle/LBMA-Statistics
version: 0.061
