--- 
abstract: "Obtain Gold and Silver Fixings (Prices) from London Bullion Market "
author: 
  - Thomas Fahle <cpan@thomas-fahle.de>
build_requires: 
  Module::Install: 0.68
  Test::Exception: 0.25
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: LBMA-Statistics
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0.41
  Encode: 2.23
  HTML::TableExtract: 2.10
  WWW::Mechanize: 1.34
version: 0.041
