---
abstract: 'Obtain Gold and Silver Fixings (Prices) from London Bullion Market '
author:
  - 'Thomas Fahle, C<< <cpan at thomas-fahle.de> >>'
  - 'Thomas Fahle <cpan@thomas-fahle.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install: 0.92
  Test::Exception: 0.25
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install: 0.92
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LBMA-Statistics
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  DateTime: 0.41
  Encode: 2.23
  HTML::TableExtract: 2.10
  Log::Log4perl: 1.30
  WWW::Mechanize: 1.34
resources:
  license: http://dev.perl.org/licenses/
version: 0.046
